"use client";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { DataTable } from "@/components/ui/data-table";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import { useAuth } from "@/providers/auth-provider";
import { reportService } from "@/services/report.service";
import { IReport } from "@/types/report.type";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ColumnDef, SortingState } from "@tanstack/react-table";
import {
  BarChart3,
  Download,
  FileBarChart,
  FileText,
  Loader2,
  MoreHorizontal,
  Plus,
  Search,
  Trash2,
  TrendingUp,
} from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function ReportsPage() {
  const { hasPermission } = useAuth();
  const queryClient = useQueryClient();
  const [isActionLoading, setIsActionLoading] = useState(false);
  const [pagination, setPagination] = useState({ pageIndex: 0, pageSize: 10 });
  const [sorting, setSorting] = useState<SortingState>([]);
  const [search, setSearch] = useState("");

  const { data, isLoading, error } = useQuery({
    queryKey: [
      "reports",
      pagination.pageIndex,
      pagination.pageSize,
      sorting,
      search,
    ],
    queryFn: () => {
      const sortParams = sorting
        .map((s) => (s.desc ? `-${s.id}` : s.id))
        .join(",");

      return reportService.getAll({
        page: pagination.pageIndex + 1,
        limit: pagination.pageSize,
        ...(sortParams ? { sort: sortParams } : {}),
        ...(search ? { search } : {}),
      });
    },
  });

  const deleteMutation = useMutation({
    mutationFn: (id: number) => reportService.delete(id),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["reports"] });
      toast.success("Analytical engine: Report purged.");
    },
    onError: (error: Error) =>
      toast.error(error.message || "Failed to purge report"),
    onSettled: () => setIsActionLoading(false),
  });

  const handleDelete = (id: number) => {
    if (confirm("Purge this analytical report from history?")) {
      setIsActionLoading(true);
      deleteMutation.mutate(id);
    }
  };

  const getReportTypeBadge = (type: string) => {
    const config: Record<string, { label: string; color: string }> = {
      leads: {
        label: "Leads Analysis",
        color: "bg-blue-500/10 text-blue-500 border-blue-500/20",
      },
      tasks: {
        label: "Task Pulse",
        color: "bg-orange-500/10 text-orange-500 border-orange-500/20",
      },
      audit: {
        label: "Security Audit",
        color: "bg-purple-500/10 text-purple-500 border-purple-500/20",
      },
      performance: {
        label: "Performance",
        color: "bg-green-500/10 text-green-500 border-green-500/20",
      },
    };

    const item = config[type] || {
      label: type,
      color: "bg-muted text-muted-foreground",
    };

    return (
      <Badge
        className={`${item.color} font-black uppercase text-[10px] tracking-tight border`}
      >
        {item.label}
      </Badge>
    );
  };

  const columns: ColumnDef<IReport>[] = [
    {
      accessorKey: "name",
      header: "Data Snapshot",
      enableSorting: true,
      cell: ({ row }) => (
        <div className="flex items-center gap-3 py-1">
          <div className="h-9 w-9 rounded-xl bg-primary/10 flex items-center justify-center text-primary">
            <FileBarChart size={18} />
          </div>
          <div className="flex flex-col">
            <span className="font-black text-foreground tracking-tight">
              {row.original.name}
            </span>
            <span className="text-[10px] text-muted-foreground uppercase font-bold tracking-widest">
              Generated by System
            </span>
          </div>
        </div>
      ),
    },
    {
      accessorKey: "type",
      header: "Domain Category",
      enableSorting: true,
      cell: ({ row }) => getReportTypeBadge(row.original.type),
    },
    {
      accessorKey: "created_at",
      header: "Archived On",
      enableSorting: true,
      cell: ({ row }) => (
        <div className="flex flex-col">
          <span className="text-xs font-bold text-foreground/80">
            {new Date(row.original.created_at).toLocaleDateString()}
          </span>
          <span className="text-[10px] text-muted-foreground font-medium">
            {new Date(row.original.created_at).toLocaleTimeString([], {
              hour: "2-digit",
              minute: "2-digit",
            })}
          </span>
        </div>
      ),
    },
  ];

  if (hasPermission("manage_reports")) {
    columns.push({
      id: "actions",
      header: () => <div className="text-right">Export</div>,
      enableSorting: false,
      cell: ({ row }) => {
        const report = row.original;
        return (
          <div className="text-right">
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="ghost"
                  className="h-8 w-8 p-0 hover:bg-accent rounded-full transition-all"
                >
                  <MoreHorizontal className="h-4 w-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent
                align="end"
                className="w-52 rounded-2xl p-2 shadow-2xl"
              >
                <DropdownMenuLabel className="text-[10px] font-black uppercase text-muted-foreground tracking-widest px-2 py-1">
                  Business Intelligence
                </DropdownMenuLabel>
                <DropdownMenuItem className="rounded-xl cursor-pointer font-bold">
                  <BarChart3 className="mr-2 h-4 w-4 text-primary" />
                  View Analytics
                </DropdownMenuItem>
                <DropdownMenuItem className="rounded-xl cursor-pointer font-bold">
                  <Download className="mr-2 h-4 w-4 text-success" />
                  Download Export
                </DropdownMenuItem>
                <DropdownMenuSeparator className="my-1" />
                <DropdownMenuItem
                  className="rounded-xl cursor-pointer text-destructive focus:bg-destructive/10 font-bold"
                  onClick={() => handleDelete(report.id)}
                  disabled={isActionLoading}
                >
                  <Trash2 className="mr-2 h-4 w-4" />
                  Delete Insight
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        );
      },
    });
  }

  return (
    <div className="space-y-10 animate-in fade-in zoom-in-95 duration-700">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
        <div className="space-y-1">
          <h1 className="text-3xl font-black tracking-tight text-foreground flex items-center gap-3">
            <BarChart3 className="text-primary h-8 w-8" />
            Business Intelligence
          </h1>
          <p className="text-muted-foreground text-sm font-semibold italic">
            Extrapolate insights and drive growth with granular reporting tiers.
          </p>
        </div>
        {hasPermission("manage_reports") && (
          <Button className="h-11 px-6 rounded-2xl bg-primary hover:bg-primary/90 text-primary-foreground shadow-xl shadow-primary/20 transition-all hover:scale-105 active:scale-95 group border-b-4 border-primary/40">
            <Plus className="mr-2 h-5 w-5 transition-transform group-hover:rotate-90" />
            Synthesize Report
          </Button>
        )}
      </div>

      {/* Analytics High-level Dashboard */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        {[
          {
            label: "Total Reports",
            value: data?.meta?.total || "0",
            icon: FileText,
            color: "text-primary",
          },
          {
            label: "Recent Performance",
            value: "+12.5%",
            icon: TrendingUp,
            color: "text-success",
          },
          {
            label: "Data Integrity",
            value: "99.9%",
            icon: BarChart3,
            color: "text-blue-500",
          },
          {
            label: "Active Engine",
            value: "Realtime",
            icon: Loader2,
            color: "text-warning",
          },
        ].map((stat, i) => (
          <div
            key={i}
            className="bg-card/40 border border-border/50 rounded-2xl p-5 shadow-sm transition-all hover:-translate-y-1"
          >
            <div className="flex items-center justify-between mb-3">
              <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground/60">
                {stat.label}
              </span>
              <stat.icon
                size={16}
                className={`${stat.color} ${stat.label === "Active Engine" ? "animate-spin-slow" : ""}`}
              />
            </div>
            <p className="text-2xl font-black tracking-tighter">{stat.value}</p>
          </div>
        ))}
      </div>

      <Card className="bg-card/40 border-border/50 backdrop-blur-3xl shadow-2xl rounded-[2rem] overflow-hidden border-t-0 ring-1 ring-border/20">
        <CardHeader className="bg-muted/10 border-b border-border/40 px-8 py-6">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-6">
            <div>
              <CardTitle className="text-xl font-black italic tracking-tight">
                Saved Data Archives
              </CardTitle>
              <CardDescription className="text-xs font-bold uppercase tracking-wide opacity-70">
                Catalog of generated mission intelligence
              </CardDescription>
            </div>
            <div className="relative w-full md:w-80 group">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground group-focus-within:text-primary transition-all duration-300" />
              <Input
                placeholder="Locate intelligence report..."
                value={search}
                onChange={(e) => {
                  setSearch(e.target.value);
                  setPagination((prev) => ({ ...prev, pageIndex: 0 }));
                }}
                className="h-11 pl-10 border-border/40 bg-background/30 focus:bg-background transition-all rounded-2xl shadow-inner font-bold"
              />
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center p-24 space-y-4">
              <Loader2 className="h-10 w-10 animate-spin text-primary/40" />
              <p className="text-[10px] font-black tracking-widest uppercase text-muted-foreground animate-pulse leading-none">
                Scanning Archives...
              </p>
            </div>
          ) : error || !data ? (
            <div className="p-20 text-center space-y-4">
              <p className="text-destructive font-black text-lg underline decoration-wavy">
                Engine Stall
              </p>
              <p className="text-muted-foreground text-sm">
                Failed to connect to the analytical core storage.
              </p>
            </div>
          ) : (
            <DataTable
              columns={columns}
              data={data?.data || []}
              pageCount={data?.meta?.total_page || 1}
              pagination={pagination}
              onPaginationChange={setPagination}
              sorting={sorting}
              onSortingChange={(updater) => {
                setSorting(updater);
                setPagination((prev) => ({ ...prev, pageIndex: 0 }));
              }}
            />
          )}
        </CardContent>
      </Card>
    </div>
  );
}
